DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS game CASCADE;
DROP SCHEMA IF EXISTS content CASCADE;
DROP SCHEMA IF EXISTS school CASCADE;
DROP SCHEMA IF EXISTS assets CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;