using Escola.Application.UseCases.Students.CreateStudent;
using Escola.Domain.School;
using Escola.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Escola.Infrastructure.UseCases.Students;

/// <summary>
/// Implementation of Create Student handler in Infrastructure layer.
/// </summary>
public class CreateStudentHandler : ICreateStudentHandler
{
    private readonly EscolaDbContext _context;

    public CreateStudentHandler(EscolaDbContext context)
    {
        _context = context;
    }

    public async Task<CreateStudentResponse> Handle(CreateStudentRequest request, CancellationToken cancellationToken = default)
    {
        // Verify tenant exists
        var tenantExists = await _context.Tenants
            .AnyAsync(t => t.TenantId == request.TenantId, cancellationToken);

        if (!tenantExists)
        {
            throw new InvalidOperationException($"Tenant with ID {request.TenantId} does not exist");
        }

        // Create the student entity - normalized fields are generated by the database
        var student = new Student
        {
            StudentUuid = Guid.NewGuid(),
            TenantId = request.TenantId,
            FirstName = request.FirstName,
            LastName = request.LastName,
            BirthDate = request.BirthDate,
            Nickname = request.Nickname,
            MiddleName = request.MiddleName,
            IsActive = true,
            CreatedAt = DateTimeOffset.UtcNow,
            CreatedBy = 1 // Using admin user from seed data - TODO: Replace with actual authenticated user
        };

        _context.Students.Add(student);
        await _context.SaveChangesAsync(cancellationToken);

        return new CreateStudentResponse
        {
            StudentUuid = student.StudentUuid,
            FullName = $"{student.FirstName} {student.LastName}"
        };
    }
}
