using Escola.Application.Services;
using Escola.Application.UseCases.Students.CreateStudent;
using Escola.Domain.School;
using Escola.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Escola.Infrastructure.UseCases.Students;

/// <summary>
/// Implementation of Create Student handler in Infrastructure layer.
/// </summary>
public class CreateStudentHandler : ICreateStudentHandler
{
    private readonly EscolaDbContext _context;
    private readonly ICurrentUserService _currentUserService;

    public CreateStudentHandler(EscolaDbContext context, ICurrentUserService currentUserService)
    {
        _context = context;
        _currentUserService = currentUserService;
    }

    public async Task<CreateStudentResponse> Handle(CreateStudentRequest request, CancellationToken cancellationToken = default)
    {
        // Get current tenant ID from context
        var currentTenantId = _currentUserService.GetCurrentTenantId();
        if (!currentTenantId.HasValue)
            throw new UnauthorizedAccessException("No tenant context available");

        // Verify tenant exists and is not deleted
        var tenantExists = await _context.Tenants
            .AnyAsync(t => t.TenantId == currentTenantId.Value && t.DeletedAt == null, cancellationToken);

        if (!tenantExists)
            throw new InvalidOperationException($"Tenant does not exist or is deleted");

        // Create the student entity - normalized fields are generated by the database
        var student = new Student
        {
            StudentUuid = Guid.NewGuid(),
            TenantId = currentTenantId.Value,
            FirstName = request.FirstName,
            LastName = request.LastName,
            BirthDate = request.BirthDate,
            Nickname = request.Nickname,
            MiddleName = request.MiddleName,
            IsActive = true,
            CreatedAt = DateTimeOffset.UtcNow,
            CreatedBy = _currentUserService.GetCurrentUserId()
        };

        _context.Students.Add(student);
        await _context.SaveChangesAsync(cancellationToken);

        return new CreateStudentResponse
        {
            StudentUuid = student.StudentUuid,
            FullName = $"{student.FirstName} {student.LastName}"
        };
    }
}
